menu:
  Archives: /archives
  #tags: /tags
  About: /about
rss: /atom.xml
description: JAVA、C、C++ 技術、生活感悟
social:
  weibo: http://www.weibo.com/myhongkongzhen
  github: https://github.com/myhongkongzhen
  stack_overflow: 
  facebook: http://www.facebook.com/myhongkongzhen
  twitter: https://twitter.com/#!/Z_ZW
  google_plus: https://www.google.com/+myhongkongzhen

page_comment: false
logo: /images/logo2.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-purple 

archive_date_format: MMM D YYYY
fancybox: true

duoshuo_shortname: Z_Z.W

google_analytics: UA-70751910-1
favicon: /images/favicon-20151123105952356.ico


highlight: 
 enable: true
 line_number: true 
 tab_replace: 

#donate: 
#  enable: true
#  text: Enjoy it ? Donate me !  欣赏此文？求鼓励，求支持！
#  alipay: http://static.ixirong.com/pic/donate/alipay1.webp
#  wechat: http://static.ixirong.com/pic/donate/wechat.png
