# Header
menu:
  Blog: /#blog
  About: /about

# Site favicon
favicon: https://avatars3.githubusercontent.com/u/8141405?v=3&s=460

# Site logo
logo: https://avatars3.githubusercontent.com/u/8141405?v=3&s=460

# Enable Fancybox
fancybox: true
